language: node_js
node_js:
    - 12
cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only: # only trigger when certain branches changes
    - docs

before_install:
  - export TZ=Asia/Singapore

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  repo: chengguizi/chengguizi.github.io
  target-branch: master
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false # true
  on: # Conditional Releases with on:
    branch: docs